export const WEB3_INITIALIZING = 'WEB3_INITIALIZING'
export const WEB3_INITIALIZED = 'WEB3_INITIALIZED'
export const WEB3_FAILED = 'WEB3_FAILED'
export const WEB3_USER_DENIED = 'WEB3_USER_DENIED'

export const WALLET_CONNECTING = 'WALLET_CONNECTING'
export const WALLET_CONNECTED = 'WALLET_CONNECTED'
export const WALLET_FAILED = 'WALLET_FAILED'

export const NETWORK_ID_FETCHING = 'NETWORK_ID_FETCHING'
export const NETWORK_ID_FETCHED = 'NETWORK_ID_FETCHED'
export const NETWORK_ID_CHANGED = 'NETWORK_ID_CHANGED'
export const NETWORK_ID_FAILED = 'NETWORK_ID_FAILED'
export const NETWORK_MISMATCH = 'NETWORK_MISMATCH'

export const HTTPS_PROVIDER_SET = 'HTTPS_PROVIDER_SET'
export const WSS_PROVIDER_SET = 'WSS_PROVIDER_SET'
export const WALLET_SET = 'WALLET_SET'
